session_name: climate-salad
windows:
  - window_name: nvim
    layout: even-horizontal
    options:
      main-pane-width: 70
    shell_command_before:
      - cd ~/Code/climate-salad
    panes:
      - shell_command:
          - nvim
      - shell_command:
          - npm run dev
  - window_name: servers
    layout: tiled
    shell_command_before:
      - cd ~/Code/climate-salad
    panes:
      - shell_command:
          - cd ~/
          - meilisearch
      - shell_command:
          - ngrok http --domain=solid-duck-honestly.ngrok-free.app 3000
      - shell_command:
          - npm run test
      - shell_command:
          - npm run test
