session_name: compass
start_directory: ~/Code/compass
windows:
  - window_name: editor
    focus: true
    layout: even-horizontal
    panes:
      - shell_command:
          - nvim
  - window_name: servers
    layout: tiled
    panes:
      - shell_command:
          - yarn dev:secure
