session_name: obsidian
start_directory: /Users/michaeldijkstra/Library/Mobile Documents/iCloud~md~obsidian/Documents/Cloud
windows:
  - window_name: editor
    focus: true
    layout: even-horizontal
    panes:
      - shell_command:
          - nvim Inbox.md
